# Generated by Django 3.2.13 on 2022-05-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sector',
            field=models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Elevage', 'Elevage'), ('Bois', 'Bois'), ('Minerai', 'Minerai')], max_length=50),
        ),
    ]
