# Generated by Django 3.2.13 on 2022-05-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220504_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profil_img',
            field=models.ImageField(blank=True, upload_to='profil_img/%Y/%m/%d'),
        ),
    ]
