# Generated by Django 3.2.13 on 2022-05-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_profil_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cover_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
