# Generated by Django 3.2.13 on 2022-05-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220504_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='transformation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
