# Generated by Django 3.2.13 on 2022-05-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_product_transformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sector',
            field=models.BooleanField(default=False),
        ),
    ]
