# Generated by Django 3.2.13 on 2022-05-06 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220506_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='love',
            field=models.ManyToManyField(blank=True, related_name='loves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='products_disliked',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='api.Product'),
        ),
        migrations.AddField(
            model_name='user',
            name='products_liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to='api.Product'),
        ),
        migrations.AddField(
            model_name='user',
            name='products_loved',
            field=models.ManyToManyField(blank=True, related_name='loves', to='api.Product'),
        ),
    ]
