# Generated by Django 3.2.13 on 2022-05-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220506_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='products_disliked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='products_liked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='products_loved',
        ),
    ]
