# Generated by Django 3.2.13 on 2022-05-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220506_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, default='Sous titre du produit', max_length=255),
        ),
    ]
