# Generated by Django 3.2.13 on 2022-05-09 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.EmailField(max_length=254)),
                ('modified_by', models.EmailField(max_length=254)),
                ('is_deleted', models.BooleanField(default=False)),
                ('services', models.TextField(blank=True, verbose_name='Services')),
                ('difference_with_existence', models.TextField(blank=True, verbose_name='Difference with existents products and services')),
                ('added_value', models.CharField(blank=True, max_length=255)),
                ('created', models.BooleanField(default=False)),
                ('patented', models.BooleanField(default=False)),
                ('slug', models.CharField(blank=True, default='Sous titre du produit', max_length=255)),
                ('dislike', models.ManyToManyField(blank=True, related_name='dislikes_project', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='likes_project', to=settings.AUTH_USER_MODEL)),
                ('love', models.ManyToManyField(blank=True, related_name='loves_project', to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(blank=True, related_name='products', to='api.Product')),
            ],
            options={
                'verbose_name': 'Project idea',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
