# Generated by Django 3.2.13 on 2022-05-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='patented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, default='Sous titre du projet', max_length=255),
        ),
    ]
